### ISSUE TITLE
This out channel doesn't receive any data, is this right?

### ISSUE THREAD

**Issue by jerryan999** [jboursiquot/portscan#2]
https://github.com/jboursiquot/portscan/blob/1ce66e6f517f3c064a3ccd17566a9a5bb8b0ae65/8-pipeline/main.go#L155

**Comment by jboursiquot** [comment]
Correct, since in this example `store` is the last step in the pipeline.

**Comment by jerryan999** [comment]
@jboursiquot  Thanks!
